config/routes.rb
LeagueApp::Application.routes.draw do

  resources :players, :except => :destroy

  root 'leagues#show', defaults: {id: 1}
  
  resources :leagues, :only => [:index,:show] do
    resources :games
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :league
  belongs_to :home_player, class_name: "Player", foreign_key: "home_player_id"
  belongs_to :away_player, class_name: "Player", foreign_key: "away_player_id"

  validates_presence_of :home_player_id, :away_player_id, :home_score, :away_score
  validates_numericality_of :home_score, :away_score

  scope :by_player, ->(id) { where("home_player_id = :id OR away_player_id = :id",{id:id}) }
  scope :by_league, ->(id) { where(league_id:id) }
  scope :by_league_player, ->(league_player) { by_league(league_player.league_id).by_player(league_player.player_id) }

  validates_presence_of :league_id, :home_player_id, :away_player_id, :home_score, :away_score

  def self.games_for(league)
    cache_key = "games-#{league.id}-#{by_league(league.id).maximum(:updated_at)}-#{by_league(league.id).count}"
    Rails.cache.fetch(cache_key) { by_league(league.id) }
  end

  def self.cached_by_league_player(league_player)
    cache_key = "#{by_league_player(league_player)}-#{by_league_player(league_player).maximum(:updated_at)}-#{by_league_player(league_player).count}"
    Rails.cache.fetch(cache_key) {by_league_player(league_player).to_a}
  end

  def home_won?
    home_score > away_score
  end

  def away_won?
    away_score > home_score
  end

  def tie?
    home_score == away_score
  end

  def home_lost?
    home_score < away_score
  end

  def away_lost?
    away_score < home_score
  end

  def process
    process_game_result
    league_home_player.save!
    league_away_player.save!
    save!
  end

  def league_home_player
    LeaguePlayer.cached_league_player(league_id,home_player_id)
  end

  def league_away_player
    LeaguePlayer.cached_league_player(league_id,away_player_id)
  end

  def league_elo_home_player
    league_home_player.to_elo
  end

  def league_elo_away_player
    league_away_player.to_elo
  end

  def process_game_result
    if home_won?
      league_elo_home_player.wins_from(league_elo_away_player)
    elsif away_won?
      league_elo_home_player.loses_from(league_elo_away_player)
    else #tie
      league_elo_home_player.plays_draw(league_elo_away_player)
    end
    league_home_player.update_score(league_elo_home_player)
    league_away_player.update_score(league_elo_away_player)
  end


end

# == Schema Information
#
# Table name: games
#
#  id             :integer          not null, primary key
#  home_player_id :integer
#  away_player_id :integer
#  home_score     :decimal(10, 2)
#  away_score     :decimal(10, 2)
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_league
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = @league.games
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @players = @league.players
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    @players = @league.players
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.league_id = params[:league_id]
    @players = @league.players
    respond_to do |format|
      if @game.process
        format.html { redirect_to @league, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    @players = @league.players
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @league, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:home_player_id, :away_player_id, :home_score, :away_score)
    end

    def set_league
      @league = League.find params[:league_id]
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for([@league,@game]) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player_home_id, "Home Player" %><br>
    <%= f.collection_select  :home_player_id, @players, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :player_away_id, "Away Player" %><br>
    <%= f.collection_select  :away_player_id, @players, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :home_score %><br>
    <%= f.text_field :home_score %>
  </div>
  <div class="field">
    <%= f.label :away_score %><br>
    <%= f.text_field :away_score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1><%= @league.name.humanize %> Games </h1>

<table>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.player.name %></td>
        <td><%= game.player.name %></td>
        <td><%= game.home_score %></td>
        <td><%= game.home_score %></td>
        <td><%= game.away_score %></td>
        <td><%= game.away_score %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', league_games_path(@league) %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Player home:</strong>
  <%= @game.player_home_id %>
</p>

<p>
  <strong>Player away:</strong>
  <%= @game.player_away_id %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @game.home_score %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @game.home_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @game.away_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @game.away_score %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>